### PR TITLE
custom-roles: fix multi-node rust example

### LINKED ISSUE #564: custom roles: fix multi node rust example
The multi-node rust example is broken on the custom roles PR:
https://github.com/aranya-project/aranya/actions/runs/18889214720/job/53912538319?pr=267
```
2025-10-28T22:37:48.294931Z  INFO admin: waiting for owner to assign admin role
2025-10-28T22:37:48.295240Z ERROR aranya_runtime::vm_policy: Could not seal command: check
2025-10-28T22:37:48.295275Z ERROR aranya_daemon::api: error=unable to query team roles

Caused by:
    engine error: panic
2025-10-28T22:37:48.294974Z  INFO roles:RPC: SendRequest rpc.deadline=2025-10-28T22:37:58.294941626Z otel.kind="client" otel.name=DaemonApi.team_roles rpc.trace_id=00
2025-10-28T22:37:48.295358Z  INFO roles:RPC: ReceiveResponse rpc.deadline=2025-10-28T22:37:58.294941626Z otel.kind="client" otel.name=DaemonApi.team_roles rpc.trace_id=00
2025-10-28T22:37:48.295375Z  INFO Shutdown: write half closed, and no requests in flight.
Error: daemon error

Caused by:
    unable to query team roles
    
    Caused by:
        engine error: panic

thread 'tokio-runtime-worker' panicked at examples/rust/aranya-example-multi-node/src/bin/main.rs:80:13:
ExitStatus(unix_wait_status(256))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
./run.bash: line 56: 18115 Aborted                 (core dumped) "${example}" "${release}" "${workspace}"
```

cc: @djohnson-spideroak, @jdygert-spok, @chip-so

### PR DESCRIPTION
**Pull request by jdygert-spok**
Closes #564.

### CODE REVIEW

File: crates/aranya-daemon/src/api.rs [hunk 1]
```diff
@@ -851,6 +851,30 @@ impl DaemonApi for Api {
...
+            .add_label_managing_role(label_id.into_id().into(), managing_role_id.into_id().into())
+            .await
+            .context("unable to add label managing role")?;
+        if let Some(Effect::LabelManagingRoleAdded(_e)) =
+            find_effect!(&effects, Effect::LabelManagingRoleAdded(_e))
+        {
+            Ok(())
+        } else {
+            Err(anyhow!("unable to add label managing role").into())
+        }
```
Comment (gknopf-aranya) [inline crates/aranya-daemon/src/api.rs:875]: Could be simplified to:
```suggestion
        if let Some(Effect::LabelManagingRoleAdded(_e)) =
            find_effect!(&effects, Effect::LabelManagingRoleAdded(_e)) else
        {
            Err(anyhow!("unable to add label managing role").into())
        }
        Ok(())
```

File: examples/rust/aranya-example-multi-node/run.bash [hunk 2]
```diff
@@ -22,35 +22,17 @@ pushd ../../../
...
-for device in "${devices[@]}"; do
-    echo "Building aranya-example-multi-node-${device}..."
-    cargo build \
-        --release \
-        --manifest-path Cargo.toml \
-        --bin aranya-example-multi-node-"${device}" \
-        --features afc \
-        --locked
-done
+echo "Building binaries..."
```
Comment (gknopf-aranya) [inline examples/rust/aranya-example-multi-node/run.bash:25]: While this is simpler, it's less clear what binaries are being built without looking them up in the `Cargo.toml`

File: examples/rust/aranya-example-multi-node/src/admin/main.rs [hunk 3]
```diff
@@ -91,13 +91,16 @@ async fn main() -> Result<()> {
...
     // Loop until this device has the `Admin` role assigned to it.
     info!("admin: waiting for owner to assign admin role");
-    let admin_role = team
-        .roles()
-        .await?
-        .iter()
-        .find(|r| r.name == "admin")
-        .ok_or_else(|| anyhow::anyhow!("no admin role"))?
-        .clone();
+    let admin_role = 'outer: loop {
```
Comment (gknopf-aranya) [inline examples/rust/aranya-example-multi-node/src/admin/main.rs]: Should we provide a method in the Rust API that makes it easier for a user to lookup a role by name?

File: examples/rust/aranya-example-multi-node/src/owner/main.rs [hunk 4]
```diff
@@ -71,6 +73,19 @@ async fn main() -> Result<()> {
...
     info!("owner: created team: {}", team_id);
 
+    {
+        let roles = team.roles().await.expect("could not query roles");
+        let mut roles = roles.iter();
+        let owner_role = roles.next().expect("missing role");
+        if roles.next().is_some() {
+            panic!("unexpected roles");
+        }
+        assert_eq!(owner_role.name, "owner");
```
Comment (gknopf-aranya) [inline examples/rust/aranya-example-multi-node/src/owner/main.rs:83]: Assuming that the first role returned is the owner seems fragile

File: crates/aranya-daemon/src/api.rs (hunk 1 above)
Comment (gknopf-aranya) [reply crates/aranya-daemon/src/api.rs:875]: Could even use `.is_some()` or `.is_none()` I believe

File: crates/aranya-client/src/client/team.rs [hunk 5]
```diff
@@ -399,6 +399,26 @@ impl Team<'_> {
...
+    pub async fn add_label_managing_role(
+        &self,
+        label_id: LabelId,
+        managing_role_id: RoleId,
+    ) -> Result<()> {
+        self.client
+            .daemon
+            .add_label_managing_role(
+                context::current(),
+                self.id,
```
Comment (gknopf-aranya) [inline crates/aranya-client/src/client/team.rs:413]: Nit: it could be more clear to change the name of the field to `team_id`:
```suggestion
                self.team_id,
```
I had to look up other code to figure out that it's not a device, label, or role ID.
Contextually this may be somewhat obvious so feel free to disregard.

File: examples/rust/aranya-example-multi-node/run.bash (hunk 2 above)
Comment (gknopf-aranya) [reply examples/rust/aranya-example-multi-node/run.bash:25]: We could add documentation on all the binaries built to the `README.md` so it's clear.

File: crates/aranya-daemon/src/api.rs (hunk 1 above)
Comment (jdygert-spok) [reply crates/aranya-daemon/src/api.rs:875]: I'm just copying the existing pattern, all these will be cleaned up in #560.

File: examples/rust/aranya-example-multi-node/run.bash (hunk 2 above)
Comment (jdygert-spok) [reply examples/rust/aranya-example-multi-node/run.bash:25]: We can see we are building the daemon and all binaries in the aranya-example-multi-node package. I don't think it's important for them to be listed here.

File: examples/rust/aranya-example-multi-node/src/owner/main.rs (hunk 4 above)
Comment (jdygert-spok) [reply examples/rust/aranya-example-multi-node/src/owner/main.rs:83]: This assumes and validates that there is only a single role, the owner. No roles should have been added yet.

File: examples/rust/aranya-example-multi-node/src/admin/main.rs (hunk 3 above)
Comment (jdygert-spok) [reply examples/rust/aranya-example-multi-node/src/admin/main.rs]: I think we probably don't want to promote looking up roles by name. They should probably be returned from onboarding.

File: examples/rust/aranya-example-multi-node/src/admin/main.rs [hunk 6]
```diff
@@ -91,13 +91,16 @@ async fn main() -> Result<()> {
...
+        if let Ok(roles) = team.roles().await {
+            for role in roles {
+                if role.name == "admin" {
+                    break 'outer role;
+                }
+            }
```
Comment (chip-so) [inline examples/rust/aranya-example-multi-node/src/admin/main.rs:98]: Is there a reason you prefer this over `.iter().find()`? This feels a lot less obvious to me.

Comment (jdygert-spok) [reply examples/rust/aranya-example-multi-node/src/admin/main.rs:98]: I suppose that's a bit nicer.

File: examples/rust/aranya-example-multi-node/src/admin/main.rs (hunk 3 above)
Comment (jdygert-spok) [reply examples/rust/aranya-example-multi-node/src/admin/main.rs]: Consolidating discussion https://github.com/orgs/aranya-project/discussions/570

**Review by gknopf-aranya — APPROVED** [review]
