### PR TITLE
Simplify error checking in integration tests

### LINKED ISSUE #716: test: use more concise matches! for checking error types in unit tests
Unit test error checking could be made more concise with `matches!` instead of the `match` statement when checking error types.

`matches!`
```                                                                                                            
let r = owner_team                                                                                                               
    .device(devices.membera.id)                                                                                                  
    .assign_role(roles.operator().id)                                                                                            
    .await;                                                                                                                      
                                                                                                                                 
assert!(matches!(r, Err(aranya_client::Error::Aranya(_))));                  
```

`match` & `bail!`
```                                                                                                      
match owner_team
    .device(devices.membera.id)
    .assign_role(roles.operator().id)
    .await
{
    Ok(_) => bail!("Expected role assignment to fail"),
    Err(aranya_client::Error::Aranya(_)) => {}
    Err(_) => bail!("Unexpected error"),
}
```

cc: @djohnson-spideroak, @jdygert-spok, @chip-so

### PR DESCRIPTION
**Pull request by gknopf-aranya**
## Summary
- Replace 22 verbose `match`/`bail!` error-checking patterns with concise `expect_err()` + `assert!(matches!(...))` in integration tests
- Add `"{err:?}"` to all assert messages for better failure diagnostics
- Remove `Error::Ipc` alternatives now that #685 is merged
- Remove resolved `TODO(#299)` comments
- No functional changes to test logic

Resolves #716

### CODE REVIEW

File: crates/aranya-client/tests/tests.rs [hunk 1]
```diff
@@ -100,15 +100,12 @@ async fn test_sync_now() -> Result<()> {
...
         .device(devices.operator.id)
         .assign_role(roles.operator().id)
         .await
-    {
-        Ok(_) => bail!("Expected role assignment to fail"),
-        Err(aranya_client::Error::Aranya(_)) => {}
-        Err(_) => bail!("Unexpected error"),
-    }
+        .expect_err("admin has not synced yet, role assignment should fail");
+    assert!(matches!(err, aranya_client::Error::Aranya(_)));
```
Comment (jdygert-spok) [inline crates/aranya-client/tests/tests.rs]:
```suggestion
    assert!(matches!(err, aranya_client::Error::Aranya(_)), "{err:?}");
```
Let's add the errors to the assert message so we can see them when it fails.

File: crates/aranya-client/tests/tests.rs [hunk 2]
```diff
@@ -674,24 +668,24 @@ async fn test_add_team() -> Result<()> {
...
-        }
+        // TODO(#299): This should fail "immediately" with an `Aranya(_)` sync error,
+        // but currently the handshake timeout races with the tarpc timeout.
+        let err = admin
+            .sync_now(owner_addr, None)
+            .await
+            .expect_err("syncing should fail before add_team()");
+        assert!(matches!(
+            err,
+            aranya_client::Error::Aranya(_) | aranya_client::Error::Ipc(_)
```
Comment (jdygert-spok) [inline crates/aranya-client/tests/tests.rs]: I think we can remove the Ipc check now after #685

File: crates/aranya-client/tests/tests.rs (hunk 1 above)
Comment (gknopf-aranya) [reply crates/aranya-client/tests/tests.rs]: Done — added `"{err:?}"` to all 22 `assert!(matches!(...))` calls.

File: crates/aranya-client/tests/tests.rs (hunk 2 above)
Comment (gknopf-aranya) [reply crates/aranya-client/tests/tests.rs]: Good call — removed all 3 `Error::Ipc` alternatives and the associated `TODO(#299)` comments since #685 is merged.
