### PR TITLE
capi-example: use the abs path like the daemon does

### LINKED ISSUE #309: capi: c example silently fails in multiple ways

### PR DESCRIPTION
**Pull request by jdygert-spok**
Closes #309.

### CODE REVIEW

**Comment by jdygert-spok** [comment]
I don't think so, I printed out the key in both client and daemon.

**Comment by elagergren-spideroak** [comment]
> I don't think so, I printed out the key in both client and daemon.

ah, the `info` parameters are differnt

**Comment by elagergren-spideroak** [comment]
> > I don't think so, I printed out the key in both client and daemon.
> 
> ah, the `info` parameters are differnt

the client is using a relative path, the daemon is using an abs path

File: crates/aranya-daemon/src/api.rs [hunk 1]
```diff
@@ -141,7 +141,7 @@ impl DaemonApiServer {
         let server = {
             let listener = UnixListener::bind(&self.uds_path)?;
             info!(
-                addr = ?listener
+                path = ?listener
```
Comment (elagergren-spideroak) [inline crates/aranya-daemon/src/api.rs]: I assume `local_addr` will return the exact same path you gave to `bind`, but it's probably a bit cleaner to just log `uds_path`.

Comment (jdygert-spok) [reply crates/aranya-daemon/src/api.rs]: Yeah see #286

Comment (elagergren-spideroak) [reply crates/aranya-daemon/src/api.rs]: especially b/c that's what's used to create `info`

**Comment by jdygert-spok** [comment]
I guess it still has a leak in CI that isn't detected locally

**Review by gknopf-aranya — DISMISSED** [review]

**Review by gknopf-aranya — APPROVED** [review]

**Review by ssweetney-spok — APPROVED** [review]
