### PR TITLE
sync: fix hello sync flake and implement builder pattern

### LINKED ISSUE #700: hello sync: init subscriptions with config instead of duration params
Passing in a config to initialize sync hello subscriptions is more self-documenting than passing in a list of `Duration` parameters. For example, the following code shows clearly what each parameter means:
```
      1276 -            Duration::from_secs(60),   // graph_change_delay                                                             
      1277 -            Duration::from_secs(120),  // duration                                                                       
      1278 -            Duration::from_millis(10), // schedule_delay - low                                                           
      1276 +            HelloSubscriptionConfig::builder()                                                                           
      1277 +                .graph_change_delay(Duration::from_secs(60))                                                             
      1278 +                .expiration(Duration::from_secs(120))                                                                    
      1279 +                .periodic_interval(Duration::from_millis(10))                                                            
      1280 +                .build()?, 
```

Use a builder pattern for the config type so it can be modified in a backward compatible way.

https://github.com/aranya-project/aranya/pull/699#discussion_r2729012263

cc: @djohnson-spideroak, @benz-spideroak, @jdygert-spok

### PR DESCRIPTION
**Pull request by gknopf-aranya**
Fixes test flakes in test_hello_subscription caused by subscriptions expiring before tests completed on slower machines running parallel tests.                                                                                                                    

Replaces individual duration parameters in sync_hello_subscribe with a HelloSubscriptionConfig struct that provides:               

- Builder pattern for configuration                                                                                                
- Sensible defaults (100ms graph change delay, 10s periodic interval, 1 year expiration)                                           
- Clearer parameter names (periodic_interval instead of schedule_delay)                                                            

The long default expiration (1 year) prevents the subscription timeout flakes, while callers can still customize via the builder.

Closes #700

### CODE REVIEW

File: crates/aranya-client/tests/tests.rs [hunk 1]
```diff
@@ -996,9 +996,9 @@ async fn test_hello_subscription() -> Result<()> {
         .sync_hello_subscribe(
             admin_addr,
             Duration::from_millis(100),
-            Duration::from_millis(1000),
-            Duration::from_secs(60), // Schedule delay for periodic sends
-        ) // Short delay for faster testing
+            Duration::from_secs(120), // Duration long enough for test to complete
```
Comment (gknopf-aranya) [inline crates/aranya-client/tests/tests.rs]: It's difficult to tell what each of these Durations are without looking up the definition of `sync_hello_subscribe()`. Seems like it would be clearer if we passed in a config struct with named fields. That way it's clear that this is setting the sync hello subscription expiration time.

Comment (gknopf-aranya) [reply crates/aranya-client/tests/tests.rs]: Planning to open a follow-up PR for this since it's out of scope for the flake fix.

Comment (gknopf-aranya) [reply crates/aranya-client/tests/tests.rs]: https://github.com/aranya-project/aranya/issues/700

File: crates/aranya-client/src/client/team.rs [hunk 2]
```diff
@@ -174,19 +169,17 @@ impl Team<'_> {
...
         self.client
             .daemon
             .sync_hello_subscribe(
                 context::current(),
                 peer,
                 self.id,
-                graph_change_delay,
-                duration,
-                schedule_delay,
+                config.graph_change_delay,
```
Comment (gknopf-aranya) [inline crates/aranya-client/src/client/team.rs]: Eventually, we could pass the config type directly into the daemon IPC and internal daemon implementation. However, the goal of this PR is to improve clarity/usability of the application API.

File: crates/aranya-client/tests/tests.rs [hunk 3]
```diff
@@ -995,10 +995,10 @@ async fn test_hello_subscription() -> Result<()> {
     membera_team
         .sync_hello_subscribe(
             admin_addr,
-            Duration::from_millis(100),
-            Duration::from_millis(1000),
-            Duration::from_secs(60), // Schedule delay for periodic sends
-        ) // Short delay for faster testing
+            HelloSubscriptionConfig::builder()
+                .graph_change_delay(Duration::from_millis(100))
```
Comment (gknopf-aranya) [inline crates/aranya-client/tests/tests.rs]: What happened to the rest of the durations that were configured here previously?

Comment (gknopf-aranya) [reply crates/aranya-client/tests/tests.rs]: Oh, the defaults were being used. It would be more clear to make them explicit in tests.

File: .github/workflows/correctness.yml [hunk 4]
```diff
@@ -32,10 +32,9 @@ jobs:
 
       - name: Install newer clang-format
         run: |
-          sudo apt-get install -y lsb-release wget software-properties-common gnupg
-          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
-          sudo apt-get install -y clang-format-20
-          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-20 200
+          sudo apt-get update
```
Comment (gknopf-aranya) [inline .github/workflows/correctness.yml]: Revert

File: examples/c/example.c [hunk 5]
```diff
@@ -260,7 +260,7 @@ AranyaError init_team(Team *t) {
 
     Client *owner = &t->clients.owner;
     Client *admin = &t->clients.admin;
-    Client *operator = &t->clients.operator;
+    Client *operator= & t->clients.operator;
```
Comment (gknopf-aranya) [inline examples/c/example.c]: Revert

File: examples/rust/aranya-example/src/main.rs [hunk 6]
```diff
@@ -293,17 +293,28 @@ async fn main() -> Result<()> {
...
         info!("admin subscribing to hello notifications from owner");
-        let duration = Duration::from_secs(30);
-        let graph_change_delay = Duration::from_millis(1000);
-        let schedule_delay = Duration::from_secs(5);
         admin_team
-            .sync_hello_subscribe(owner_addr, graph_change_delay * 2, duration, schedule_delay)
+            .sync_hello_subscribe(
+                owner_addr,
+                HelloSubscriptionConfig::builder()
+                    .graph_change_delay(Duration::from_millis(2000))
```
Comment (gknopf-aranya) [inline examples/rust/aranya-example/src/main.rs]: Why was graph change delay increased?

File: examples/c/example.c [hunk 7]
```diff
@@ -719,19 +719,38 @@ AranyaError run(Team *t) {
...
     printf("admin subscribing to hello notifications from owner\n");
-    AranyaDuration graph_change_delay = ARANYA_DURATION_SECONDS * 1ULL;
-    AranyaDuration duration = ARANYA_DURATION_SECONDS * 30ULL;
-    AranyaDuration schedule_delay = ARANYA_DURATION_SECONDS * 5ULL;
+    AranyaHelloSubscriptionConfigBuilder hello_cfg_builder;
+    AranyaHelloSubscriptionConfig hello_cfg;
+    err = aranya_hello_subscription_config_builder_init(&hello_cfg_builder);
+    EXPECT("error initializing hello subscription config builder", err);
+    aranya_hello_subscription_config_builder_set_graph_change_delay(
+        &hello_cfg_builder, ARANYA_DURATION_SECONDS * 2ULL);
```
Comment (gknopf-aranya) [inline examples/c/example.c]: Why was graph change delay increased?

File: examples/c/example.c [hunk 8]
```diff
@@ -719,19 +719,38 @@ AranyaError run(Team *t) {
...
-                                      schedule_delay);
+                                      &hello_cfg);
     EXPECT("error subscribing admin to owner hello notifications", err);
 
     // Operator subscribes to hello notifications from Admin with 1-second delay
     printf("operator subscribing to hello notifications from admin\n");
+    err = aranya_hello_subscription_config_builder_init(&hello_cfg_builder);
+    EXPECT("error initializing hello subscription config builder", err);
+    aranya_hello_subscription_config_builder_set_graph_change_delay(
+        &hello_cfg_builder, ARANYA_DURATION_SECONDS * 1ULL);
```
Comment (gknopf-aranya) [inline examples/c/example.c]: Graph change delay used to be `graph_change_delay * 2` which would be `2ULL`.

File: examples/rust/aranya-example/src/main.rs (hunk 6 above)
Comment (gknopf-aranya) [reply examples/rust/aranya-example/src/main.rs]: Oh, this was `graph_change_delay * 2` so it's correct.

File: crates/aranya-client/src/client/team.rs (hunk 2 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/client/team.rs]: Added a TODO comment for this.

File: crates/aranya-client/src/client/team.rs [hunk 9]
```diff
@@ -174,19 +169,19 @@ impl Team<'_> {
     pub async fn sync_hello_subscribe(
         &self,
         peer: Addr,
-        graph_change_delay: Duration,
-        duration: Duration,
-        schedule_delay: Duration,
+        config: crate::config::HelloSubscriptionConfig,
```
Comment (ssweetney-spok) [inline crates/aranya-client/src/client/team.rs:172]: Shouldn't this go in a new method like `sync_hello_subscribe_with_config` in order to maintain backwards compatibility?

File: crates/aranya-client/src/config.rs [hunk 10]
```diff
@@ -119,3 +119,100 @@ impl Default for SyncPeerConfigBuilder {
...
+
+/// Configuration for hello subscription.
+///
+/// This configures how a device subscribes to hello notifications from a sync peer.
+/// Hello notifications inform subscribers when the peer's graph has changed,
+/// enabling reactive syncing.
+#[cfg(feature = "preview")]
+#[cfg_attr(docsrs, doc(cfg(feature = "preview")))]
+#[derive(Clone, Debug)]
+pub struct HelloSubscriptionConfig {
```
Comment (ssweetney-spok) [inline crates/aranya-client/src/config.rs:131]: If these fields are gonna be public then this type should be marked with `#[non_exhaustive]` or add a private field so that adding new fields won't break code.

The other config types we define, like `aranya_client::config::SyncPeerConfig`, have don't have public fields. Why is this one different?

File: crates/aranya-client/src/client/team.rs (hunk 9 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/client/team.rs:172]: Sync hello is still behind `preview`, so we can break backward compatibility.

File: crates/aranya-client/src/config.rs (hunk 10 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs:131]: Good point. This should be implemented in a similar way as the other public types so future changes can be made in a backward compatible way. Even though we're allowed to break the hello sync API for now since it's behind the `preview` flag, we want to be mindful about designing in the API in a way where future changes can be made in a backward compatible way. Using the builder pattern for the config gets us closer to that goal by not hard-coding subscription params in a function.

Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs:131]: I've updated this to private fields with getter methods so the type cannot be externally constructed. `HelloSubscriptionConfig` is a config type like `SyncPeerConfig`, so private fields without #[non_exhaustive] is consistent with the existing pattern. The current change follows the established convention.

File: examples/c/example.c [hunk 11]
```diff
@@ -719,19 +719,38 @@ AranyaError run(Team *t) {
...
+    EXPECT("error initializing hello subscription config builder", err);
+    aranya_hello_subscription_config_builder_set_graph_change_delay(
+        &hello_cfg_builder, ARANYA_DURATION_SECONDS * 2ULL);
+    aranya_hello_subscription_config_builder_set_expiration(
+        &hello_cfg_builder, ARANYA_DURATION_SECONDS * 30ULL);
+    aranya_hello_subscription_config_builder_set_periodic_interval(
+        &hello_cfg_builder, ARANYA_DURATION_SECONDS * 5ULL);
+    err =
+        aranya_hello_subscription_config_build(&hello_cfg_builder, &hello_cfg);
+    EXPECT("error building hello subscription config", err);
```
Comment (jdygert-spok) [inline examples/c/example.c]: This is so verbose, and we aren't even handling the errors from the setters :/

File: crates/aranya-client/src/config.rs [hunk 12]
```diff
@@ -119,3 +119,111 @@ impl Default for SyncPeerConfigBuilder {
...
+    }
+
+    /// Sets how long the subscription remains active before expiring.
+    ///
+    /// After this duration, the subscription will automatically end and no more
+    /// hello notifications will be sent. Default is 120 seconds.
+    pub fn expiration(mut self, duration: Duration) -> Self {
+        self.expiration = duration;
+        self
+    }
```
Comment (jdygert-spok) [inline crates/aranya-client/src/config.rs:216]: Are there even many situations you want your subscription to time out? This should probably default to none/MAX.

File: examples/c/example.c (hunk 11 above)
Comment (gknopf-aranya) [reply examples/c/example.c]: The example could use a `_default()` method to set up the config. If a user wants to configure something other than the defaults, they can set those values case-by-case. That would help to shorten this example and keep it focused on setting up the subscription.

File: crates/aranya-client/src/config.rs (hunk 12 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs:216]: That is a question that was discussed during the initial hello sync design. We intentionally made the sync subscription time a required parameter to ensure subscriptions eventually expire. The goal of this PR isn't to change that behavior but to switch from fixed parameters to a builder pattern for the sync hello config.

Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs:216]: MAX seems like a decent default given that shorter times are arbitrary.

File: .clang-format [hunk 13]
```diff
@@ -1,4 +1,8 @@
 ---
+Language: Cpp
```
Comment (gknopf-aranya) [inline .clang-format]: This resolves the issue where `operator` is considered a C++ keyword when formatting the example.c file:
```
  + xargs -0 -- clang-format --Werror --dry-run                                                                                      
  examples/c/example.c:263:21: error: code should be clang-formatted [-Wclang-format-violations]                                     
  Client *operator= & t->clients.operator;                                                                                           
  ^   
```

Comment (jdygert-spok) [reply .clang-format]: I don't get what you mean. That error is correctly complaining that the code is not formatted right. If I run clang-format on it with the original .clang-format config it formats it as `Client *operator = &t->client.operator;` as it should.

File: crates/aranya-client-capi/src/imp/config.rs [hunk 14]
```diff
@@ -154,3 +154,110 @@ impl Default for SyncPeerConfigBuilder {
...
+
+#[cfg(feature = "preview")]
+impl From<HelloSubscriptionConfig> for aranya_client::HelloSubscriptionConfig {
+    fn from(value: HelloSubscriptionConfig) -> Self {
+        aranya_client::HelloSubscriptionConfig::builder()
+            .graph_change_delay(value.graph_change_delay.into())
+            .expiration(value.expiration.into())
+            .periodic_interval(value.periodic_interval.into())
+            .build()
+            .expect("All values are set")
```
Comment (gknopf-aranya) [inline crates/aranya-client-capi/src/imp/config.rs:189]: Shouldn't panic here

File: .clang-format (hunk 13 above)
Comment (gknopf-aranya) [reply .clang-format]: When I ran the formatting it didn't match what is in CI until after I made this change.

File: crates/aranya-client/tests/tests.rs
Comment (gknopf-aranya) [inline crates/aranya-client/tests/tests.rs:1]: Tests can be simplified to use defaults except for configurations where specific values matter. E.g. default 1yr subscription that doesn't expire.

File: .clang-format (hunk 13 above)
Comment (jdygert-spok) [reply .clang-format]: This change shouldn't have any effect. With no language specified, the config applies to all languages.

Comment (gknopf-aranya) [reply .clang-format]: It does for me. I haven't been able to get my local dev machine or sp1 to format the same way as CI for some time. This finally worked.

File: crates/aranya-client-capi/src/imp/config.rs (hunk 14 above)
Comment (gknopf-aranya) [reply crates/aranya-client-capi/src/imp/config.rs:189]: It's infallible and matches our existing conventions for builder patterns.

File: crates/aranya-client/tests/tests.rs
Comment (gknopf-aranya) [reply crates/aranya-client/tests/tests.rs:1]: Updated tests to use defaults when possible. Only sets specific values where needed.

File: crates/aranya-client/tests/tests.rs [hunk 15]
```diff
@@ -1168,9 +1149,11 @@ async fn test_hello_subscription_schedule_delay() -> Result<()> {
     membera_team
         .sync_hello_subscribe(
             admin_addr,
-            Duration::from_secs(60),  // graph_change_delay
-            Duration::from_secs(120), // duration
-            Duration::from_secs(60),  // schedule_delay - high
+            HelloSubscriptionConfig::builder()
+                .graph_change_delay(Duration::from_secs(60))
+                .expiration(Duration::from_secs(120))
```
Comment (gknopf-aranya) [inline crates/aranya-client/tests/tests.rs]: Use default

File: examples/rust/aranya-example/src/main.rs [hunk 16]
```diff
@@ -293,17 +293,28 @@ async fn main() -> Result<()> {
 
         // Admin subscribes to hello notifications from Owner with 2-second delay
         info!("admin subscribing to hello notifications from owner");
-        let duration = Duration::from_secs(30);
-        let graph_change_delay = Duration::from_millis(1000);
-        let schedule_delay = Duration::from_secs(5);
         admin_team
-            .sync_hello_subscribe(owner_addr, graph_change_delay * 2, duration, schedule_delay)
+            .sync_hello_subscribe(
```
Comment (gknopf-aranya) [inline examples/rust/aranya-example/src/main.rs]: Why not use defaults here?

Comment (gknopf-aranya) [reply examples/rust/aranya-example/src/main.rs]: Updated to use defaults

File: .clang-format (hunk 13 above)
Comment (jdygert-spok) [reply .clang-format]: Weird. What's your version? Mine:

```
> which -a clang-format
/opt/homebrew/bin/clang-format
> clang-format --version
clang-format version 21.1.7
```

Comment (gknopf-aranya) [reply .clang-format]: A little older than yours:
```
gknopf@sp1:~/scm/aranya$ clang-format --version
Ubuntu clang-format version 20.1.8 (++20250708083436+6fb913d3e2ec-1~exp1~20250708203453.133)
```
```
gknopf@geoffreys-macbook-pro aranya % clang-format --version
clang-format version 18.1.6
```

Comment (jdygert-spok) [reply .clang-format]: clang-format-18 errors out with this change since it doesn't support `C` for the language field.
clang-format-20 seems to format it just fine to me. IDK what's making our tools behave differently.

Comment (gknopf-aranya) [reply .clang-format]: idk, but I'm tired of the fmt being different and this finally helped.

Comment (gknopf-aranya) [reply .clang-format]: Except now the code analysis is failing in CI...

Comment (jdygert-spok) [reply .clang-format]: The code QL stuff is unrelated, I had fiddled with that and thought it was working but now it's trying to autobuild again even though the default is supposed to be the mode that doesn't build at all...

Comment (jdygert-spok) [reply .clang-format]: Well, it was working in a previous run on this PR and I haven't touched it since then :thinking:

Comment (jdygert-spok) [reply .clang-format]: I guess it never switched off from autobuild, but the autobuild is just flaky :/

Comment (jdygert-spok) [reply .clang-format]: Turned the C CodeQL back off since it's just causing issues for little gain.

Comment (jdygert-spok) [reply .clang-format]: I only get formatting issues with clang-format-18, which there is just no way to avoid AFAICT. Does it not format for you correctly with clang-format-20 on main?

Comment (gknopf-aranya) [reply .clang-format]: Don't know. I just upgraded to the latest which is 21.

Comment (gknopf-aranya) [reply .clang-format]: Same issue after upgrading:
```
gknopf@geoffreys-macbook-pro aranya % cargo make fmt
gknopf@geoffreys-macbook-pro aranya % git diff
diff --git a/examples/c/example.c b/examples/c/example.c
index d6bdcba7..05b7e54e 100644
--- a/examples/c/example.c
+++ b/examples/c/example.c
@@ -260,7 +260,7 @@ AranyaError init_team(Team *t) {
 
     Client *owner = &t->clients.owner;
     Client *admin = &t->clients.admin;
-    Client *operator = &t->clients.operator;
+    Client *operator= & t->clients.operator;
     Client *membera = &t->clients.membera;
     Client *memberb = &t->clients.memberb;
 
@@ -443,8 +443,9 @@ AranyaError init_team(Team *t) {
     }
 
     // add operator to team.
-    err = aranya_add_device_to_team(&owner->client, &t->id, operator->pk,
-                                    operator->pk_len, &operator_role_id);
+    err = aranya_add_device_to_team(&owner->client,
+                                    &t->id, operator->pk, operator->pk_len,
+                                    &operator_role_id);
     if (err != ARANYA_ERROR_SUCCESS) {
         fprintf(stderr, "unable to add operator to team\n");
         return err;
@@ -671,7 +672,7 @@ AranyaError run(Team *t) {
     AranyaDeviceId *devices = NULL;
 
     Client *admin = &t->clients.admin;
-    Client *operator = &t->clients.operator;
+    Client *operator= & t->clients.operator;
     Client *memberb = &t->clients.memberb;
 
     // initialize logging.
```

Comment (gknopf-aranya) [reply .clang-format]: Then I checkout this branch and get:
```
[cargo-make] INFO - Running Task: fmt-c
/Users/gknopf/scm/aranya/.clang-format:6:11: error: unknown enumerated scalar
Language: C
```

Comment (gknopf-aranya) [reply .clang-format]: It doesn't look like `Language: C` is valid:
```
Fixed. The issue was that Language: C is not a valid clang-format option - C code is handled by Language: Cpp. I removed the       
  redundant section since both had identical settings.

❯ Will this work for clang-format 20 as well?                                                                                        
                                                                                                                                     
⏺ Yes. Language: Cpp has always been the standard way to format C code in clang-format - it covers C, C++, Objective-C, and          
  Objective-C++. This hasn't changed and there's no indication it will. Language: C has never been a valid option in any clang-format
   version.   
```

Comment (jdygert-spok) [reply .clang-format]: I had to look this up when I set up clang-format initially for CI. `Language: C` was added in clang-format-20. Compare the documentation for the two versions. This means you must still be running an older version somehow?

https://releases.llvm.org/20.1.0/tools/clang/docs/ClangFormatStyleOptions.html#language
https://releases.llvm.org/18.1.1/tools/clang/docs/ClangFormatStyleOptions.html#language

Comment (gknopf-aranya) [reply .clang-format]: The problem is happening because `operator` is a reserved C++ variable. I think we should rename the variable if we want to have consistent formatting and not use a reserved word.

File: .github/workflows/correctness.yml [hunk 17]
```diff
@@ -34,8 +34,8 @@ jobs:
         run: |
           sudo apt-get install -y lsb-release wget software-properties-common gnupg
           sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
-          sudo apt-get install -y clang-format-20
-          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-20 200
+          sudo apt-get install -y clang-format-21
```
Comment (gknopf-aranya) [inline .github/workflows/correctness.yml]: Revert this

File: .clang-format (hunk 13 above)
Comment (gknopf-aranya) [reply .clang-format]: It was using the old version even though I installed the new one. symlinks and paths needed to be updated. Appears to work now.

File: crates/aranya-client-capi/src/api/defs.rs [hunk 18]
```diff
@@ -1875,30 +1986,24 @@ pub unsafe fn remove_sync_peer(
...
 /// @relates AranyaClient.
 #[cfg(feature = "preview")]
 pub unsafe fn sync_hello_subscribe(
     client: &Client,
     team: &TeamId,
     peer: Addr,
-    graph_change_delay: Duration,
-    duration: Duration,
-    schedule_delay: Duration,
+    config: &HelloSubscriptionConfig,
```
Comment (jdygert-spok) [inline crates/aranya-client-capi/src/api/defs.rs]: If we expect using the defaults to be reasonable, let's make this optional so you can pass null to use the defaults.

File: crates/aranya-client-capi/output/aranya-client.h [hunk 19]
```diff
@@ -1589,6 +1619,196 @@ AranyaError aranya_sync_peer_config_builder_set_sync_on_hello_ext(struct AranyaS
...
+ * - graph_change_delay: 100ms
+ * - expiration: 1 year
+ * - periodic_interval: 10 seconds
+ *
+ * @param[out] out a pointer to write the config to
+ *
+ * @relates AranyaHelloSubscriptionConfig.
+ */
+AranyaError aranya_hello_subscription_config_default(struct AranyaHelloSubscriptionConfig *out);
+#endif
```
Comment (jdygert-spok) [inline crates/aranya-client-capi/output/aranya-client.h]: We can remove this convenience function if we make the param optional.

File: crates/aranya-client/src/client/team.rs [hunk 20]
```diff
@@ -174,19 +169,19 @@ impl Team<'_> {
...
     ) -> Result<()> {
+        // TODO: Pass the config type directly into the daemon IPC and internal
+        // daemon implementation instead of extracting individual fields here.
```
Comment (djohnson-spideroak) [inline crates/aranya-client/src/client/team.rs]: This PR or another?

File: crates/aranya-client/src/config.rs [hunk 21]
```diff
@@ -119,3 +119,115 @@ impl Default for SyncPeerConfigBuilder {
...
+impl HelloSubscriptionConfig {
+    /// Creates a default [`HelloSubscriptionConfigBuilder`].
+    pub fn builder() -> HelloSubscriptionConfigBuilder {
+        Default::default()
+    }
+
+    /// Minimum delay after a graph change before sending a hello notification.
+    pub fn graph_change_delay(&self) -> Duration {
+        self.graph_change_delay
+    }
```
Comment (jdygert-spok) [inline crates/aranya-client/src/config.rs]: I know the name and possibly description were pre-existing, but they are off from how we are currently using it. Currently this is the amount of time after sending a notification in which no notification will be sent upon graph change.

I think we want this to ideally behave like a debounce so we could just call and describe it as that.

File: crates/aranya-client/src/client/team.rs (hunk 20 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/client/team.rs]: A different PR. This PR has already increased in scope from the original goal of fixing a test flake. I want to nail down the API now in case this feature is moved out from behind the preview flag since this is an API improvement. Internal changes like this can happen later.

File: crates/aranya-client/src/config.rs (hunk 21 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs]: Renaming seems out of scope of the current PR. This is focused on solving a flake and making API improvements. A rename would affect naming throughout the repo and seems better suited for a stand-alone PR.

File: crates/aranya-client/src/client/team.rs (hunk 20 above)
Comment (djohnson-spideroak) [reply crates/aranya-client/src/client/team.rs]: Lets have an issue to track the changes.

File: crates/aranya-client/src/config.rs (hunk 21 above)
Comment (djohnson-spideroak) [reply crates/aranya-client/src/config.rs]: I am fine doing the rename in a followup as long as we have an issue for it.

Comment (jdygert-spok) [reply crates/aranya-client/src/config.rs]: The name wasn't part of the public API before this change. We could just change it in this new builder method.

File: crates/aranya-client/src/client/team.rs (hunk 20 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/client/team.rs]: Here's an issue for it:
https://github.com/aranya-project/aranya/issues/709

File: crates/aranya-client/src/config.rs (hunk 21 above)
Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs]: That would work. Mostly want to stabilize whatever part of the API that cannot change after we move this out from behind a feature flag.

Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs]: Is the suggestion to call this `graph_change_debounce`?

Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs]: Renaming everywhere requires a change to the sync protocol. I can rename in client/daemon code here. Mostly a find-replace operation.

Comment (jdygert-spok) [reply crates/aranya-client/src/config.rs]: Yeah something like that. That sounds fine.

Comment (jdygert-spok) [reply crates/aranya-client/src/config.rs]: It's fine if you want to limit the change to the public API of the rust and C builder.

Comment (gknopf-aranya) [reply crates/aranya-client/src/config.rs]: claude made it a little faster, so I'll tackle it here

**Comment by gknopf-aranya** [comment]
@jdygert-spok ready for another look
